### ISSUE TITLE
Change the mechanics of the build target.

### ISSUE THREAD

**Issue by kotbegemot** [smart-cloud/actor-zeta#21]
now after building the project two targets: actor-zetta-core , actor-zeta-io .
There should be one target actor-zeta.
Add checkboxes that tell cmake which components to include in the final build of the library.
By default, all library components are enabled.

Add build options:
- [x] shared = off
- [x] rtti = off
- [x] exception = off
- [x] CMake_RUN_CLANG_TIDY = off
- [x] example = off
- [x] dev mode = off
- [x] test = off

**Comment by petrovigor** [comment]
IO can't build itself without CORE, so I'll remove CORE check, leave IO option. Also I'll add STATIC/SHARED option for the actor-zeta target.

**Comment by kotbegemot** [comment]
check box : IO,STATIC/SHARED
@petrovigor you want so ?

**Comment by petrovigor** [comment]
Yes, let user chose STATIC/SHARED build.
And only one additional functionality for "IO".

**Comment by petrovigor** [comment]
It's done. See for pull request #23.

**Comment by kotbegemot** [comment]
@petrovigor 
1. Why was the replacement?
list(APPEND -> set(
2. Why can't I use a multi-target system?

**Comment by petrovigor** [comment]
Okay, please review and ask questions. #23
